version: '3.8'

services:
  xmrt_asset_tokenizer_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules  # Prevent node_modules override
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    networks:
      - xmrt-dev-network

networks:
  xmrt-dev-network:
    driver: bridge
