name: Performance Monitoring

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * *'  # Daily performance check

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run performance benchmarks
      run: |
        npm run benchmark || npm run test:performance || echo "No performance tests configured"
    
    - name: Generate performance report
      run: |
        echo "Performance report for xmrt-asset-tokenizer" > performance-report.txt
        # Add performance metrics
    
    - name: Upload performance artifacts
      uses: actions/upload-artifact@v3
      with:
        name: performance-reports
        path: |
          performance-report.txt
          benchmarks/
  
  resource-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Analyze resource usage
      run: |
        npm run build\ndu -sh dist/ node_modules/\necho "Node.js resource analysis completed"
    
    - name: Check bundle size (if applicable)
      if: contains('TypeScript', 'JavaScript') || contains('TypeScript', 'TypeScript')
      run: |
        npm run build
        npx bundlesize
  
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository health check
      run: |
        echo "Repository: xmrt-asset-tokenizer"
        echo "Language: TypeScript"
        echo "Complexity Score: 20"
        echo "Health Status: Monitoring"
